### ISSUE TITLE
Неверный путь

### ISSUE THREAD

**Issue by slugaboga** [webasyst/dummy-theme#7]
Добрый день.
При попытке вставить список товаров в шаблон сайта, выдало ошибку.
Пробовал переключать между темами, ошибка остается.
По этому адресу все файлы присутствуют.

`SmartyException: Unable to load template file 'products.html' in '/home3/www/public_html/wa-data/public/shop/themes/mysite/list-thumbs.html' in /home3/www/public_html/wa-system/vendors/smarty3/sysplugins/smarty_internal_templatebase.php:133
Stack trace:
#0 /home3/www/public_html/wa-system/vendors/smarty3/sysplugins/smarty_internal_template.php(286): Smarty_Internal_TemplateBase->fetch(Object(Smarty_Internal_Template), NULL, NULL, NULL, false, false, true)
#1 /home3/www/public_html/wa-cache/apps/site/templates/compiled/site_ru_RU/8a/3a/5c/8a3a5cb959b44fba71897c1a19dc324b02d6de49.file.list-thumbs.html.php(22): Smarty_Internal_Template->getSubTemplate('products.html', NULL, 'site_ru_RU', NULL, NULL, Array, 0)
#2 /home3/www/public_html/wa-system/vendors/smarty3/sysplugins/smarty_internal_templatebase.php(186): content_5e96b96c381934_97393239(Object(Smarty_Internal_Template))
#3 /home3/www/public_html/wa-system/vendors/smarty3/sysplugins/smarty_internal_template.php(286): Smarty_Internal_TemplateBase->fetch(Object(Smarty_Internal_Template), NULL, NULL, NULL, false, false, true)
#4 /home3/www/public_html/wa-cache/apps/site/templates/compiled/site_ru_RU/2c/37/8f/2c378fcae95ca5214883b26360f9437716508110.string.php(36): Smarty_Internal_Template->getSubTemplate('/home3/www...', NULL, 'site_ru_RU', NULL, NULL, Array, 0)
#5 /home3/www/public_html/wa-system/vendors/smarty3/sysplugins/smarty_internal_templatebase.php(186): content_5e96b96c112f04_80103638(Object(Smarty_Internal_Template))
#6 /home3/www/public_html/wa-system/view/waSmarty3View.class.php(144): Smarty_Internal_TemplateBase->fetch('string:`

Код файла list-thumbs.html
`{include file="products.html" inline}`
меняю на это, ошибка уходит
`{include file="./products.html" inline}`

но при попытке купить товар из списка, появляется другая ошибка
`CSRF Protection code 403
## wa-system/waSystem.class.php(936)
#0 wa-system/waSystem.class.php(615): waSystem->dispatchFrontend('my/')
#1 index.php(7): waSystem->dispatch()
#2 {main}`

**Comment by mikeushenin** [comment]
> При попытке вставить список товаров в шаблон сайта

В какой именно шаблон вставили? Покажите свой код, который вы вставили.

**Comment by slugaboga** [comment]
`{if $wa->shop}
{$products = $wa->shop->productSet("bestsellers")}
{include file="`$wa->shop->themePath('mytheme')`list-thumbs.html" products=$products}
{/if}`

**Comment by slugaboga** [comment]
> В какой именно шаблон вставили? Покажите свой код, который вы вставили.

index.html

{if $wa->shop} {$products = $wa->shop->productSet("bestsellers")} {include file="$wa->shop->themePath('mytheme')list-thumbs.html" products=$products} {/if}

**Comment by mikeushenin** [comment]
> $wa->shop->themePath('**mytheme**')

В сообщении об ошибке в самом начале нет упоминания темы с идентификатором `mytheme`, но есть упоминание идентификатора темы `mysite`. Из какой темы дизайна вы пытаетесь подключить файл _list-thumbs.html_: `mytheme` или `mysite`?
